services:
  scene-recorder:
    image: scene-recorder
    build: .
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_CATEGORIES_JSON=["Category 1", "Category 2"]
      - NEXT_PUBLIC_UNIVERSES_JSON=[1,2,3,4]
      - NEXT_PUBLIC_PRIO=90
      - PORT=3000