services:
  scene-recorder:
    image: scene-recorder
    build: .
    ports:
      - 3000:3000
    environment:
      - CATEGORIES_JSON=["Category 1", "Category 2"]
      - UNIVERSES_JSON=[1,2,3,4]
      - SACN_PRIORITY=90
      - PORT=3000